# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "rag-system-tfstate"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
