# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy   = "terragrunt"
      Environment = var.environment
      Project     = "rag-system"
    }
  }
}
